---
title: "CompProject2"
author: "Patrick Wong"
date: "11/07/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MATH 324 Computer Project 2

### Algorithm 1: Generate 500 Sample Means from Sample Size n and for a Particular Distribution

###I)
```{r}
library(ggplot2)
a <- 0
b <- 5
sample_size <- 500
numList <- runif(sample_size, min = a, max = b)
```
###II)
```{r}
number_trials <- 15
p <- 0.2
rbinom(sample_size, size = number_trials, prob = p)
```
###III)
```{r}
lambda <- 5
rexp(sample_size, rate = lambda)
```
###IV)
```{r}
mu <- 2
rpois(sample_size, mu)
```
###Algorithm)
```{r}
storedData = rep(NA, sample_size)
for (i in 1:sample_size){
  storedData[i] = i
  print(storedData[i])
}
```
###Question 1)
```{r}
# if the sample size is 5
n <- 5
simulatedData5 <- matrix(rexp(n*sample_size, lambda), nrow=sample_size, ncol=n)
simMeans5 <- apply(simulatedData5, 1, mean)
sampleMean5 <- round(mean(simMeans5),3);
paste0("sampleMean for n = 5: " , sampleMean5)
theoreticalMean5 <- round(1/lambda,3);
paste0("theoreticalMean for n = 5: ", theoreticalMean5)


# if the sample size is 50
m <- 50
simulatedData50 <- matrix(rexp(m*sample_size, lambda), nrow=sample_size, ncol=m)
simMeans50 <- apply(simulatedData50, 1, mean)
sampleMean50 <- round(mean(simMeans50),3);
paste0("sampleMean for n = 50: " , sampleMean50)
theoreticalMean50 <- round(1/lambda,3);
paste0("theoreticalMean for n = 50: ", theoreticalMean50)
```

###Question 2)
```{r}
## if the sample size is 5
simulatedData5 <- matrix(rexp(n*sample_size, lambda), nrow=sample_size, ncol=n)
simMeans5 <- apply(simulatedData5, 1, mean)
sampleVar5 <- round(var(simMeans5), 3)
paste0("sampleVariance for n = 5: ", sampleVar5)
theoretcalVar5 <- round((1/lambda)^2/n,3);
paste0("theoreticalVariance for n = 5: ", theoretcalVar5)

## if the sample size is 50 
simulatedData50 <- matrix(rexp(m*sample_size, lambda), nrow=sample_size, ncol=m)
simMeans50 <- apply(simulatedData50, 1, mean)
sampleVar50 <- round(var(simMeans50), 3)
paste0("sampleVariance for n = 50: ", sampleVar50)
theoretcalVar50 <- round((1/lambda)^2/n,3);
paste0("theoreticalVariance for n = 50: ", theoretcalVar50)
```
###Question 3)
```{r}
hist(simMeans5, col="snow", main="Histogram of 500 means of 5 sample exponentials", xlab="Sample Mean", ylab="Frequency")
abline(v=sampleMean5, col="green", lwd=6, lty=2)
abline(v=theoreticalMean5, col="red", lwd=3)

hist(simMeans50, col="azure2", main="Histogram of 500 means of 50 sample exponentials", xlab="Sample Mean", ylab="Frequency");
abline(v=sampleMean50, col="blue", lwd=6, lty=2)
abline(v=theoreticalMean50, col="yellow", lwd=3)
```

###Question 4)
```{r}
qqnorm(simMeans5)
qqline(simMeans5)

qqnorm(simMeans50)
qqline(simMeans50)
```